### ISSUE TITLE
Upgrade to SinonJS 1.17.2

### ISSUE THREAD

**Issue by Radagaisus** [matthijsgroen/konacha-chai-matchers#8]
Hey,

The current SinonJS version in this repository is `1.12.2`, and the latest is `1.17.2`. I've just upgraded our test suites to use konacha-chai-matchers 1.0.0, and two tests that used `sinon.useFakeTimers()` started failing. It looks to be this https://github.com/sinonjs/sinon/issues/621 or similar. In any case, upgrading sinon to 1.7.2 fixed the issue.

**Comment by bradbirnbaum** [comment]
I am also bumping into this +1

**Comment by GurpreetSran** [comment]
+1 , same issue.

**Comment by matthijsgroen** [comment]
I don't know when I will have the time to do this, but of course I'm ready to accept pull requests
